config/routes.rb
Rails.application.routes.draw do
  get 'user/index' => 'user#index'
  get 'photo/index/:id' => 'photo#index', as: 'user_photos'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  has_many :photos
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController
  def index
    @user = User.find_by(id: params[:id])
    @photos = Photo.where(user_id: params[:id])
    @comments = Comment.all
    # @user_all = User.all
  end
  def display_name(user_id)
    @user = User.find_by(id: user_id)
    return @user.first_name
  end
  helper_method :display_name
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
    @users = User.all()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSiteApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/photo/index.html.erb
<h1>PHOTOS BY: <%= @user.first_name %><% @user.last_name %></h1>
<body>
<% @photos.each do |photo| %>
  <div>
    <%= image_tag photo.url %>
    Photo Posted on
    <%= photo.date_time %>
    <h2>Comments:</h2>
    <% @comments.where("photo_id=?",photo.id).each do |comment| %>
      <div>
        <li>
          <%= comment.comment_text %>
          --Posted By:
          <% @user = User.find(comment.user_id) %>
          <%= link_to display_name(comment.user_id),user_photos_path(comment.user_id)%>
          on
          <%= comment.date_time %>
        </li>
      </div>
    <% end %>
  </div>
<% end %>
</body>

app/views/user/index.html.erb
<h1>Photosite User List Information</h1>
<body>
<table>
  <tr>
    <th>User</th>
    <th>First Name</th>
    <th>Last Name</th>
  </tr>
  <% for user in @users %>
    <tr>
      <td> <%= user.id %></td>
      <td> <%= link_to user.first_name, {:action => "index", :controller => "photo", :id => user.id} %></td>
      <td> <%= user.last_name %></td>
    </tr>
  <% end %>
</table>
</body>